axis_linear: 
   x: 1
   y: 0

scale_linear: 
   x: 0.7
   y: 0.7

scale_linear_turbo: 
   x: 1.5
   y: 1.5

axis_angular: 
   yaw: 2

scale_angular: 
   yaw: 0.4

scale_angular_turbo:
  yaw: 0.6

enable_button: 1
enable_turbo_button: 0

